# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/projects/school/cp431/Parallel-ARM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/projects/school/cp431/Parallel-ARM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/projects/school/cp431/Parallel-ARM/CMakeFiles /home/alex/projects/school/cp431/Parallel-ARM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/projects/school/cp431/Parallel-ARM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named find-rules

# Build rule for target.
find-rules: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 find-rules
.PHONY : find-rules

# fast build rule for target.
find-rules/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/build
.PHONY : find-rules/fast

Apriori.o: Apriori.c.o
.PHONY : Apriori.o

# target to build an object file
Apriori.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/Apriori.c.o
.PHONY : Apriori.c.o

Apriori.i: Apriori.c.i
.PHONY : Apriori.i

# target to preprocess a source file
Apriori.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/Apriori.c.i
.PHONY : Apriori.c.i

Apriori.s: Apriori.c.s
.PHONY : Apriori.s

# target to generate assembly for a file
Apriori.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/Apriori.c.s
.PHONY : Apriori.c.s

dynamic_hash_table.o: dynamic_hash_table.c.o
.PHONY : dynamic_hash_table.o

# target to build an object file
dynamic_hash_table.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/dynamic_hash_table.c.o
.PHONY : dynamic_hash_table.c.o

dynamic_hash_table.i: dynamic_hash_table.c.i
.PHONY : dynamic_hash_table.i

# target to preprocess a source file
dynamic_hash_table.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/dynamic_hash_table.c.i
.PHONY : dynamic_hash_table.c.i

dynamic_hash_table.s: dynamic_hash_table.c.s
.PHONY : dynamic_hash_table.s

# target to generate assembly for a file
dynamic_hash_table.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/dynamic_hash_table.c.s
.PHONY : dynamic_hash_table.c.s

find-rules.o: find-rules.c.o
.PHONY : find-rules.o

# target to build an object file
find-rules.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/find-rules.c.o
.PHONY : find-rules.c.o

find-rules.i: find-rules.c.i
.PHONY : find-rules.i

# target to preprocess a source file
find-rules.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/find-rules.c.i
.PHONY : find-rules.c.i

find-rules.s: find-rules.c.s
.PHONY : find-rules.s

# target to generate assembly for a file
find-rules.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/find-rules.c.s
.PHONY : find-rules.c.s

io-processing.o: io-processing.c.o
.PHONY : io-processing.o

# target to build an object file
io-processing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/io-processing.c.o
.PHONY : io-processing.c.o

io-processing.i: io-processing.c.i
.PHONY : io-processing.i

# target to preprocess a source file
io-processing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/io-processing.c.i
.PHONY : io-processing.c.i

io-processing.s: io-processing.c.s
.PHONY : io-processing.s

# target to generate assembly for a file
io-processing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/io-processing.c.s
.PHONY : io-processing.c.s

itemset_hash_table.o: itemset_hash_table.c.o
.PHONY : itemset_hash_table.o

# target to build an object file
itemset_hash_table.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/itemset_hash_table.c.o
.PHONY : itemset_hash_table.c.o

itemset_hash_table.i: itemset_hash_table.c.i
.PHONY : itemset_hash_table.i

# target to preprocess a source file
itemset_hash_table.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/itemset_hash_table.c.i
.PHONY : itemset_hash_table.c.i

itemset_hash_table.s: itemset_hash_table.c.s
.PHONY : itemset_hash_table.s

# target to generate assembly for a file
itemset_hash_table.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/itemset_hash_table.c.s
.PHONY : itemset_hash_table.c.s

map_items.o: map_items.c.o
.PHONY : map_items.o

# target to build an object file
map_items.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/map_items.c.o
.PHONY : map_items.c.o

map_items.i: map_items.c.i
.PHONY : map_items.i

# target to preprocess a source file
map_items.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/map_items.c.i
.PHONY : map_items.c.i

map_items.s: map_items.c.s
.PHONY : map_items.s

# target to generate assembly for a file
map_items.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/map_items.c.s
.PHONY : map_items.c.s

map_lookup.o: map_lookup.c.o
.PHONY : map_lookup.o

# target to build an object file
map_lookup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/map_lookup.c.o
.PHONY : map_lookup.c.o

map_lookup.i: map_lookup.c.i
.PHONY : map_lookup.i

# target to preprocess a source file
map_lookup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/map_lookup.c.i
.PHONY : map_lookup.c.i

map_lookup.s: map_lookup.c.s
.PHONY : map_lookup.s

# target to generate assembly for a file
map_lookup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/map_lookup.c.s
.PHONY : map_lookup.c.s

rules-aux.o: rules-aux.c.o
.PHONY : rules-aux.o

# target to build an object file
rules-aux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/rules-aux.c.o
.PHONY : rules-aux.c.o

rules-aux.i: rules-aux.c.i
.PHONY : rules-aux.i

# target to preprocess a source file
rules-aux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/rules-aux.c.i
.PHONY : rules-aux.c.i

rules-aux.s: rules-aux.c.s
.PHONY : rules-aux.s

# target to generate assembly for a file
rules-aux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/find-rules.dir/build.make CMakeFiles/find-rules.dir/rules-aux.c.s
.PHONY : rules-aux.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... find-rules"
	@echo "... Apriori.o"
	@echo "... Apriori.i"
	@echo "... Apriori.s"
	@echo "... dynamic_hash_table.o"
	@echo "... dynamic_hash_table.i"
	@echo "... dynamic_hash_table.s"
	@echo "... find-rules.o"
	@echo "... find-rules.i"
	@echo "... find-rules.s"
	@echo "... io-processing.o"
	@echo "... io-processing.i"
	@echo "... io-processing.s"
	@echo "... itemset_hash_table.o"
	@echo "... itemset_hash_table.i"
	@echo "... itemset_hash_table.s"
	@echo "... map_items.o"
	@echo "... map_items.i"
	@echo "... map_items.s"
	@echo "... map_lookup.o"
	@echo "... map_lookup.i"
	@echo "... map_lookup.s"
	@echo "... rules-aux.o"
	@echo "... rules-aux.i"
	@echo "... rules-aux.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

